### ISSUE TITLE
Trying to use this but i'm getting NodeWallet not constructor

### ISSUE THREAD

**Issue by smartydev42** [rckprtr/pumpdotfun-sdk#1]
const wallet = new NodeWallet(Keypair.generate()); //note this is not used

this errors with 

 const wallet = new NodeWallet(Keypair.generate()); //note this is not used
                   ^
TypeError: NodeWallet is not a constructor

unsure what i'm doing wrong.

**Comment by newlgbtqdev** [comment]
Dealing with same error

**Comment by newlgbtqdev** [comment]
did you figure any solutions?

**Comment by rckprtr** [comment]
Can you show me the contents of `nodewallet.d.ts` ? Do you just clone the project and `npm i` it? 

```
node -v
v20.10.0
```

**Comment by newlgbtqdev** [comment]
![Capture](https://github.com/rckprtr/pumpdotfun-sdk/assets/172449441/da00c0cc-ced4-41ff-bcdb-45f07e5d866b)

Yes followed all instructions, building custom script but running in to this issue. 

Tried a workaround and ran into type error that Anchor_Wallet was missing.

**Comment by smartydev42** [comment]
for me, i didnt use commonjs within my tsconfig, that fixed it.

**Comment by rckprtr** [comment]
So the fix for the library might be using es2022 for the module and the target, which ill make the change
