### ISSUE TITLE
Unable to buy/sell - message: 'Curve is complete'

### ISSUE THREAD

**Issue by tdev00** [rckprtr/pumpdotfun-sdk#11]
@rckprtr, sorry to do this to you, but some things just don't make a lot of sense.

Let's say no modifications have been made to the createAndBuy function, and 1.5 SOL was used to initially buy tokens. The bonding curve would be completed since all the tokens have been bought.

**_Bonding Curve Account:_**

```
complete: true
discriminator: 6966180631402821399n
realSolReserves: 1469351843n  <---- 1.5 SOL (minus slippage fees or pumpfun fees?)
realTokenReserves: 0n    <---- No tokens available
tokenTotalSupply: 1000000000000000n
virtualSolReserves: 31469351843n
virtualTokenReserves: 1022900000000000n
```

I've noticed that after the tokens have been bought, the sell function won't work because this error appears:
`message: 'Curve is complete'`

**_Explanation:_**

From my understanding, the issue arises because the bonding curve mechanism is designed to indicate completion when all tokens are bought. In this scenario, spending `1.5 SOL` results in buying up all available tokens, leaving no tokens for further transactions. This state is reflected in the complete: true status in the bonding curve account. I'm assuming the issue lies in the `getBuyPrice` & `getSellPrice`.

So, when the bonding curve is marked as complete, this will not allow anymore tokens for future transactions, causing the sell function to throw the "Curve is complete" error. 

![image](https://github.com/rckprtr/pumpdotfun-sdk/assets/63981572/639adbf4-5b82-41ef-b4dc-061dc1494fcb)
![image](https://github.com/rckprtr/pumpdotfun-sdk/assets/63981572/1a3021e7-4e80-42a9-9782-c29839ee34b3)

**_Additional Details:_**

    Network: devnet
    Quicknode API
    Node.js
    
**_Code:_**
```
async function main() {
  const BUY_SOL_AMOUNT = BigInt(1.5 * LAMPORTS_PER_SOL);

  // Initialize mint key pair
  const mintKeypair = initializeMintKeypair();

  let bondingCurveAccount = await pumpFunSDK.getBondingCurveAccount(mintKeypair.publicKey);
  if (!bondingCurveAccount) {
    const result = await pumpFunSDK.createAndBuy(owner, mintKeypair, createTokenMetadata, BUY_SOL_AMOUNT);

    if (result.success) { 
      console.log('-----Success Token Created!-----');
      console.log(`https://pump.fun/${mintKeypair.publicKey.toBase58()}`);
      await getSPLBalance(mintKeypair, owner);
    }
  }
}

function initializeMintKeypair() {
  console.log('-----Initialize Mint Wallet-----');
  let mintKeypair;
  try {
    // Read from file
    const keypairInfo = getKeypairInfo();
    mintKeypair = Keypair.fromSecretKey(bs58.decode(keypairInfo.secretKey));
    console.log('Using existing keypair:', keypairInfo.publicKey);
  } catch (error) {
    console.log('No existing keypair found. Creating a new one.');
    saveMintKeypair(mint);
    mintKeypair = mint;
  }
  return mintKeypair;
}

```

**Comment by rckprtr** [comment]
Interesting, I minted a new token on devnet:

```
Bonding curve after create and buy BondingCurveAccount {
  discriminator: 6966180631402821399n,
  virtualTokenReserves: 1073000000000000n,
  virtualSolReserves: 30000000000n,
  realTokenReserves: 50100000000000n,
  realSolReserves: 0n,
  tokenTotalSupply: 1000000000000000n,
  complete: false
}
```

So I decided to check Global Params
```
GlobalAccount {
  discriminator: 9183522199395952807n,
  initialized: true,
  authority: PublicKey [PublicKey(DCpJReAfonSrgohiQbTmKKbjbqVofspFRHz9yQikzooP)] {
    _bn: <BN: b5531d6246f2015e72621c71ebf9304871dd8bbcf6f6c714948be6ddbd1e6ff2>
  },
  feeRecipient: PublicKey [PublicKey(68yFSZxzLWJXkxxRGydZ63C6mHx1NLEDWmwN9Lb5yySg)] {
    _bn: <BN: 4c5519e9876412b852caf722a4281dcd6b846a0a1275d13aa2969224e85b65b1>
  },
  initialVirtualTokenReserves: 1073000000000000n,
  initialVirtualSolReserves: 30000000000n,
  initialRealTokenReserves: 50100000000000n,
  tokenTotalSupply: 1000000000000000n,
  feeBasisPoints: 100n
}
```

Then I decided to chart it out in Python
![image](https://github.com/rckprtr/pumpdotfun-sdk/assets/4605139/5769f0ea-2c91-42be-9cf5-805e64a76840)

According to that the max SOL for this bonding curve is 1.466~ SOL.  The function throws an exception when the bonding curve account is reporting the bonding curve is actually complete and Im only reading on-chain data to determine this.  It looks like pump.fun is either testing out a new curve or set the devnet to a really low threshold.

The production initial real token reserve I believe is `793100000000000` and on devnet its now `50100000000000`
