### ISSUE TITLE
Is there a way to generate token address with 'pump' at the end?

### ISSUE THREAD

**Issue by JSzafarski** [rckprtr/pumpdotfun-sdk#17]
I was wondering if this is something that can be done with the create and buy method?

Many thanks.

**Comment by rckprtr** [comment]
Yes,

https://www.quicknode.com/guides/solana-development/getting-started/how-to-create-a-custom-vanity-wallet-address-using-solana-cli

**Comment by 0xwckd** [comment]
I mined a vanity keypair ends with 'pump' and launched the token successfully, but the token cannot be viewed on pump.fun. Any idea?
