### ISSUE TITLE
Token details

### ISSUE THREAD

**Issue by invokeinnovation** [rckprtr/pumpdotfun-sdk#19]
How could I find out how much the owner holds? For example I want to see if a specific mint owner holds 100% or 50% etc.

**Comment by rckprtr** [comment]
Need to grab all the token holders and determine the amount they hold relative to the total token supply.  SimpleHash API can do this for Shyft API

**Comment by chenxianqi** [comment]
I also have this problem. I run it in the Chrome browser, and there are always some WebSocket connection errors: chunk-KCB7GPR7.js?v=ff63d6b4:8850 WebSocket connection to 'wss://go.getblock.io/*****' failed:
