### ISSUE TITLE
Please add bloxroute tip

### ISSUE THREAD

**Issue by LimaTechnologies** [rckprtr/pumpdotfun-sdk#21]
https://docs.bloxroute.com/solana/trader-api-v2/front-running-protection-and-transaction-bundle

It's just a transfer of a small amount of sol to txns go really fast, plase consider that

**Comment by Jay-Frontera** [comment]
Just making a up for pinging inside your notifications

**Comment by rckprtr** [comment]
Im down to add it, Im trying to imagine how it would work... the function to buy and sell already has a ton of inputs... maybe there is a config param passed in or an option param.

**Comment by matotubol-ai** [comment]
> https://docs.bloxroute.com/solana/trader-api-v2/front-running-protection-and-transaction-bundle
> 
> 
> 
> It's just a transfer of a small amount of sol to txns go really fast, plase consider that

Do you think its faster than jito tips ?

**Comment by Jay-Frontera** [comment]
> > https://docs.bloxroute.com/solana/trader-api-v2/front-running-protection-and-transaction-bundle
> > It's just a transfer of a small amount of sol to txns go really fast, plase consider that
> 
> Is this faster than jito tips ?

Depends on how many ppl are tipping, that's why I use bloxroute, everyone uses jito by standart, but i've never mesured I just assummed that it would only have a issue based on the amount of ppl using, based on solana infra it should be the same for every single tip since we just need a validator processing and that's all, but I can be talking shit if they do something to be faster in fact

**Comment by rckprtr** [comment]
> > > https://docs.bloxroute.com/solana/trader-api-v2/front-running-protection-and-transaction-bundle
> > > It's just a transfer of a small amount of sol to txns go really fast, plase consider that
> > 
> > 
> > Is this faster than jito tips ?
> 
> Depends on how many ppl are tipping, that's why I use bloxroute, everyone uses jito by standart, but i've never mesured I just assummed that it would only have a issue based on the amount of ppl using, based on solana infra it should be the same for every single tip since we just need a validator processing and that's all, but I can be talking shit if they do something to be faster in fact

I reached out to their support.

Basically to understand if you need to use a bloxroute RPC and have a bloxroute account to benefit from any tips.

**Comment by matotubol** [comment]
Just compared the two,
helius sdk smartTransactionsWithJitoTips took like 6 seconds on average,
free tier bloxroute took 4 seconds on average,
tip amount used was 100000 lamports
tested with buy method

**Comment by rckprtr** [comment]
> Just compared the two, helius sdk smartTransactionsWithJitoTips took like 6 seconds on average, free tier bloxroute took 4 seconds on average, tip amount used was 100000 lamports tested with buy method both methods used staked connection

Thank you for looking into it, Im going to get this added as well as refactor some functions to be more intuitive.  I did not expect this repo to get the traction it did.

**Comment by AkshatGiri** [comment]
> > > https://docs.bloxroute.com/solana/trader-api-v2/front-running-protection-and-transaction-bundle
> > > It's just a transfer of a small amount of sol to txns go really fast, plase consider that
> > 
> > 
> > Is this faster than jito tips ?
> 
> Depends on how many ppl are tipping, that's why I use bloxroute, everyone uses jito by standart, but i've never mesured I just assummed that it would only have a issue based on the amount of ppl using, based on solana infra it should be the same for every single tip since we just need a validator processing and that's all, but I can be talking shit if they do something to be faster in fact

The speed of the transaction can depend on how many validators the service has / are partnered up with. Jito has ALOT of validators working with them, I believe they mine 1 out of every 3 blocks on Solana. The more validators they have, the more blocks they are mining so the chances of your transaction getting included in the block becomes higher. I haven't tried bloxroute yet, will go test it out. Thanks for the pointer!

**Comment by LimaTechnologies** [comment]
nope, but there was better open source options if you search on github
