### ISSUE TITLE
Token metadata (links)

### ISSUE THREAD

**Issue by SkullCandby** [rckprtr/pumpdotfun-sdk#22]
What is a proper way to provide links in the token?

**Comment by rckprtr** [comment]
What do you mean links? Like a URI for the metadata?

**Comment by SkullCandby** [comment]
yeah like telegram, twitter and website

**Comment by rckprtr** [comment]
Add them to the create params for the token metadata:

https://github.com/rckprtr/pumpdotfun-sdk/blob/main/src/types.ts#L13
