### ISSUE TITLE
Bonding curve account not found

### ISSUE THREAD

**Issue by wa292178** [rckprtr/pumpdotfun-sdk#23]
When I try to buy new token, it show Bonding curve account not found

**Comment by rckprtr** [comment]
Can you share some code?

**Comment by rckprtr** [comment]
Ok, that is a bit weird actually, if it continues to happen report it again. My thinking is the `commitment` levels may be different.

**Comment by SkullCandby** [comment]
I dont undestand what did you do to get the bunding curve account, I have the same problem as you
