### ISSUE TITLE
Slippage logic

### ISSUE THREAD

**Issue by matotubol-ai** [rckprtr/pumpdotfun-sdk#25]
Is the logic implementation for slippage (maxSolCost) accurate ? As there is no real documentation how pumpfun calculates it, and does it expect supply amount or lamports ?

**Comment by rckprtr** [comment]
There are no real docs, but I believe it to be accurate, I can also be wrong.  The bonding curve should define the final price and slippage should only be to ensure you are approving an amount greater or equal to that number.  So if you say the Price + Slippage = 1 SOL and the Bonding Curve determines the price is 0.5 SOL, you should only be charge 0.5 SOL.
