### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by game-swoosh** [rckprtr/pumpdotfun-sdk#28]
Does this SDK have any rate limits? I would like to send roughly 60-90 `buy` transactions at once. I looked at your code and you seem to be talking directly to the blockchain right? So if that's the case wondering if there is rate limits. 

Note: RPC I use allows more than 100 sendTransactions per second

**Comment by rckprtr** [comment]
Its straight to chain, I only provider helpers to simplify the buy and sell.

**Comment by game-swoosh** [comment]
Thank you!
