### ISSUE TITLE
createTokenMetadata

### ISSUE THREAD

**Issue by zacklif** [rckprtr/pumpdotfun-sdk#36]
Hi,
Thank you for this great sdk.

at createTokenMetadata
on fetch "https://pump.fun/api/ipfs"
the response is {"size":0,"timeout":0}
what could be the reason?

**Comment by rckprtr** [comment]
How big is the image you are uploading in MBs? Is it possible there is no image also and its an empty blob?

**Comment by zacklif** [comment]
I tried the weight check - reduced the png to 59KB and still got the same response.
I also printed the formdata and saw the file exists
when was the last time you have tried this endpoint, does it currently works for you?

**Comment by rckprtr** [comment]
yes I just ran the endpoint when I saw your bug and it worked.Are you just calling the function to create it? Can you share some code?

**Comment by zacklif** [comment]
Sure.

This is how I call the function:
    let tokenMetadataInit = {
      name: "Test",
      symbol: "TST",
      description: "This is a test",
      file: await fs.openAsBlob("./img/tst.png"),
    }

    let tokenMetadata = await createTokenMetadata(tokenMetadataInit);

    console.log("tokenMetadata: " + JSON.stringify(tokenMetadata))

    ------------------------------------------------------------------------------

    This is the function:
    
async function createTokenMetadata(tokenMetadataInit: any) {
  let formData = new FormData();
  formData.append("file", tokenMetadataInit.file),
  formData.append("name", tokenMetadataInit.name),
  formData.append("symbol", tokenMetadataInit.symbol),
  formData.append("description", tokenMetadataInit.description),
  formData.append("twitter", tokenMetadataInit.twitter || ""),
  formData.append("telegram", tokenMetadataInit.telegram || ""),
  formData.append("website", tokenMetadataInit.website || ""),
  formData.append("showName", "true");

  console.log(formData)

  /*
  // Create IPFS metadata storage
  const metadataResponse = await fetch("https://pump.fun/api/ipfs", {
      method: "POST",
      body: formData as any,
  });
  const metadataResponseJSON = await metadataResponse.json();

  return metadataResponseJSON;
*/
  
  const resp = await fetch('https://pump.fun/api/ipfs', {
    method: "POST",
    body: formData as any,
  })
  .then(response => {
    if (!response.ok) {
      console.log('Network response was not ok: ' + JSON.stringify(response));
    }
    return response.text(); // Using text() instead of json() to catch and debug the response
  })
  .then(text => {
    try {
      const data = JSON.parse(text);
      console.log(data);
      return data;
    } catch (error) {
      console.error('Error parsing JSON:', error, text);
    }
  })
  .catch(error => {
    console.error('Fetch error:', error);
  });

  return resp

}

    ------------------------------------------------------------------------------

And this it what it prints:

FormData {
  [Symbol(state)]: [
    { name: 'file', value: [File] },
    { name: 'name', value: 'Test' },
    { name: 'symbol', value: 'TST' },
    { name: 'description', value: 'This is a test' },
    { name: 'twitter', value: '' },
    { name: 'telegram', value: '' },
    { name: 'website', value: '' },
    { name: 'showName', value: 'true' }
  ]
}

Network response was not ok: {"size":0,"timeout":0}
Error parsing JSON: SyntaxError: Unexpected end of JSON input

**Comment by zacklif** [comment]
Turns out it is a typescript environment issue.
I isolated the code in a new js environment and it worked.

Thanks for your help!
