### ISSUE TITLE
Fee When Using the SDK

### ISSUE THREAD

**Issue by tranphuocanh0207** [rckprtr/pumpdotfun-sdk#37]
Currently, I want to use your SDK. However, I couldn't find any information about the fees. 
I would like to know if there are any fees applied to the SDK and what the fee per transaction is when using the SDK.

**Comment by rckprtr** [comment]
The fees are only ones associated with pumpdotfun, no fees are added to this SDK.

**Comment by tranphuocanh0207** [comment]
Wow, that's great. Thank you!
