### ISSUE TITLE
How can I get the mint keypair for pump fun tokens? Please

### ISSUE THREAD

**Issue by carol99115566** [rckprtr/pumpdotfun-sdk#47]
Such as this transaction:  https://solscan.io/tx/3r5697tJdPaHYoXoykbd6KD5jDDJ5yW9gBZJMqYU9kfDWfednzc9JxSg2caBpDAcuCHdxGHYjmYQT4Yjy4vnDJTx . 
This need the mint keypair as signer, how can i get it?
<img width="469" alt="image" src="https://github.com/user-attachments/assets/0f4714bc-ad04-4b0d-b010-a9ca4286b8ac">

**Comment by saraspaudel** [comment]
@carol99115566 did you figure out what was the answer to this?
