### ISSUE TITLE
False Error: Curve is complete

### ISSUE THREAD

**Issue by om7** [rckprtr/pumpdotfun-sdk#48]
Hello, after I launched a token I was able to make 10 or so buys, but when the curve reached about 50% now I'm getting this error: Error: Curve is complete.

What would explain the mismatch between the pumfun website and the sdk?  Any way to get around this?

**Comment by datnguyen-tech** [comment]
Do you know what "Curve is complete" is? Can you explain it to me? Thank you

**Comment by SeasonsLi** [comment]
Any body know what is the meaning of "binding curve"? pls tell me, thanks
