### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toBuffer')

### ISSUE THREAD

**Issue by joip1** [rckprtr/pumpdotfun-sdk#5]
I'm getting this error while trying to call the getBuyInstructions function:

<img width="809" alt="image" src="https://github.com/rckprtr/pumpdotfun-sdk/assets/42916568/6e4f9ff9-374d-4f32-95cb-b15cf9774fbe">
<img width="1489" alt="image" src="https://github.com/rckprtr/pumpdotfun-sdk/assets/42916568/2283284f-c0be-4592-a4ad-091f838e7e39">

**Comment by rckprtr** [comment]
Its Javascript, I believe you must call the function like this: 

```

(async () => {
  console.log("Creating a wallet");

  let buyInstructions = await pumpFunSDK.getBuyInstructions(
    _wallet.publicKey,
    new PublicKey(token_mint),
    new PublicKey(PUMP_FUN_FEE_RECIPIENT),
    100, //tokenAmount you wish to spend so 100 tokens for example
    BigInt(sol_amount*10**9), //Max SOL amount in LAMPORTs you wish to spend.
  );

  console.log("buyInstructions", buyInstructions);
})();

```

The way your calling it is passing in that object as a the first param and thus `mint` is null and throwing an exception.

Second the amount field is a `Token Amount` you wish to buy and second Param is the `maxSolAmount` you're willing to pay to purchase that amount of tokens.  Next `getBuyInstructions` is async, so you need to `await` it.

Curious, why not just use the `buy` function?

**Comment by joip1** [comment]
Hey, going to try that right now. To answer your question, the reason i'm not using the buy function is because I want to generate a new transaction that I can sign and use in a jito bundle, therefore I only require the signed transaction as a base58 string, Do you have any idea of how I can do this using the sdk in a more efficient way? Thank you!

**Comment by rckprtr** [comment]
Check out this PR: https://github.com/rckprtr/pumpdotfun-sdk/pull/6

I think this helper might make it easier. LMK
